### PR TITLE
Doctor Appointment Backened

### PR DESCRIPTION
**Pull request by Lul-Abdifan**
Dear Reviewer,

In this final capstone, a team of four people has participated in bringing the requirement to life

- Abdi @Lul-Abdifan 
- Elham @Elhambasir 
- MD Mursedul @sumon766  
- James @serengia 

The Front-End repository is [here](https://github.com/sumon766/frontend-doctor-appointment)

We chose a Doctor theme to implement the Appointment of Doctor for this capstone project.

The major features implemented are listed as follows.

#### Backend side
- Create a Database for our project
- Create User, Doctor,Appointment Controllers and Model with its all crud functionality
- Add devise authentication
- Generate API endpoints
- Add API documentation

#### Front-End side
- User Registration:
  -  Patients can register to gain access to the main page.

- User Login:
  - Users can log in using their unique username and password.

- Doctor Lists:

  - Users can browse a list of doctors added by the admin. Clicking on a doctor's name will lead to their individual page.
- Single Doctor Data:

  - Users can view detailed information about a single doctor and make appointments by clicking the "Reserve Single Doctor" button.
 -  Appointment Page:

    - A page displaying available doctors, cities, and dates, allowing users to schedule appointments with ease.
- My Appointments Page:

  - A page that lists the appointments made by patients.
- Add Doctor:

  - Users or admins have the ability to add new doctors by providing their name, description, and a photo.
-  Delete Doctor:

  - Users or admins can delete doctor entries as needed.

-  Added Navigation for all pages with its mobile version
- Made Responsiveness for all pages

### CODE REVIEW

**Comment by serengia** [comment]
Hello @Meltrust . We have implemented all the changes but we are unable to send another review request because the status of our project in the Dashboard still says "REVIEW RATING PENDING", kindly assist.

**Comment by Meltrust** [comment]
> Hello @Meltrust . We have implemented all the requested changes but we are unable to send another review request because the status of our project in the Dashboard still says "REVIEW RATING PENDING", kindly assist.

Contacted on Slack to offer support.

**Review by Meltrust — CHANGES_REQUESTED** [review]
Hi @Lul-Abdifan,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:


-  Superfluous "test" folder has been removed ✔️ 
-  Tests section has been added to readme✔️ 
-  Controllers have more consistent error handling ✔️ 




#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

You can do it

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

**Review by Meltrust — APPROVED** [review]
#### Hi @Lul-Abdifan,


# **Wow, you did it 🎉**
Brilliant
## Thank you for the changes implemented 💪 🥇 ㊗️ 
#### _Unless you want to add more features, go ahead to your final presentation ⏩ ⏩ ⏩_ 
## You are about to finish the Microverse program.  You have come a long way!!!




### Good luck in the software industry!!  I'll see you there. ✨
### **Congratulations!!!!!!**  🎉
applause




Cheers and Happy coding!👏👏👏


------

**Comment by Lul-Abdifan** [comment]
We appreciate the constructive feedback. Thank you for all

**Pull request closed without merging**
